apps:bot:
  - "### Which (application|package|application or package) is this (bug
    report|feature request) for\\?\\n\\nbot\\n"
packages:eslint-config-galaxity:
  - "### Which (application|package|application or package) is this (bug
    report|feature request) for\\?\\n\\neslint-config-galaxity\\n"
packages:@galaxity/tsconfig:
  - "### Which (application|package|application or package) is this (bug
    report|feature request) for\\?\\n\\n@galaxity/tsconfig\\n"
