apps:bot:
  - apps/bot/*
  - apps/bot/**/*
ci:
  - .github/workflows/*
  - .github/workflows/**/*
dependencies:
  - package.json
  - pnpm-lock.yaml
  - apps/**/package.json
  - packages/**/package.json
packages:eslint-config-galaxity:
  - packages/eslint-config-galaxity/*
  - packages/eslint-config-galaxity/**/*
packages:@galaxity/tsconfig:
  - packages/tsconfig/*
  - packages/tsconfig/**/*
tools:
  - tools/*
  - tools/**/*
