version: '3.3'
services:
  bot:
    container_name: bot
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile.bot
    env_file:
      - .env.production
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
