version: '3.3'
services:
  bot:
    container_name: bot
    image: slekup/galaxity:main
    env_file:
      - .env.production
    restart: always
    # depends_on:
    #   - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
