blank_issues_enabled: false
contact_links:
  - name: GitHub Discussion
    url: https://github.com/slekup/galaxity/discussions
    about: Ask questions and get direct support in our discussion forum.
