# index 0 = default, 1 = premium limit (ms)
cooldown:
  global: [100, 100]
  slash: [500, 500]
  prefix: [500, 500]
  context: [500, 500]
  button: [500, 500]
  selectMenu: [500, 500]
  modal: [5000, 2500]
