productionId: 1090549575766511667
status: Crunching numbers!

links:
  invite: https://discord.com/oauth2/authorize?client_id=1090549575766511667&scope=bot%20applications.commands&permissions=8
  support: https://discord.gg/galaxity
  vote: https://discord.gg/galaxity # TODO: Add vote link

developers:
  - '896657711104667719'

colors:
  primary: '#E265FD'
  success: '#00FF00'
  warning: '#FF9609'
  danger: '#FF0000'
  blurple: '#535EEC'

images:
  banner: https://i.imgur.com/HCya0RU.png
